name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - 'py/**/*.py'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Setup dependencies cache
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install pipreqs and other tools
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller==5.13.2 pywin32 pefile pipreqs
      shell: pwsh

    - name: Check dependencies in code and requirements.txt
      run: |
        # 检查代码中的依赖库
        Write-Host "Checking libraries used in the code..."
        $codeDependencies = pipreqs py --print
        Write-Host "Dependencies found in the code:"
        Write-Host $codeDependencies

        # 检查 requirements.txt 是否存在
        if (Test-Path "py/requirements.txt") {
          Write-Host "requirements.txt found, comparing with code dependencies..."
          $reqFileDependencies = Get-Content py/requirements.txt
          
          Write-Host "Existing requirements.txt dependencies:"
          Write-Host $reqFileDependencies

          # 找出代码中新增的依赖项
          $missingDependencies = Compare-Object -ReferenceObject $reqFileDependencies -DifferenceObject $codeDependencies | 
                                  Where-Object { $_.SideIndicator -eq '=>' } | 
                                  ForEach-Object { $_.InputObject }

          if ($missingDependencies) {
            Write-Host "New dependencies to install:"
            Write-Host $missingDependencies
          } else {
            Write-Host "No new dependencies found."
          }
        } else {
          Write-Host "No requirements.txt found, all dependencies from code will be installed."
          $missingDependencies = $codeDependencies
        }

        # 安装所有依赖
        if ($missingDependencies) {
          Write-Host "Installing missing dependencies..."
          foreach ($dependency in $missingDependencies) {
            try {
              pip install $dependency --upgrade
            } catch {
              Write-Host "Failed to install $dependency"
              exit 1
            }
          }
        } else {
          Write-Host "No dependencies to install."
        }
      shell: pwsh

    - name: Install dependencies from requirements.txt
      run: |
        if (Test-Path "py/requirements.txt") {
          Write-Host "Installing dependencies from requirements.txt..."
          pip install -r py/requirements.txt --upgrade
          pip freeze  # 输出已安装库的列表
        } else {
          Write-Host "No requirements.txt found, skipping this step."
        }
      shell: pwsh

    - name: Generate or update requirements.txt
      run: |
        Write-Host "Updating requirements.txt..."
        
        # 确保 py 目录存在并且包含 Python 文件
        if (-not (Test-Path "py") -or -not (Get-ChildItem "py/*.py" -ErrorAction SilentlyContinue)) {
          Write-Error "No Python files found in 'py' directory."
          exit 1
        }

        # 生成或更新 requirements.txt 文件
        try {
          pipreqs py --force --output py/requirements.txt
          Write-Host "Generated/Updated requirements.txt successfully."
        } catch {
          Write-Error "Error while generating requirements.txt: $_"
          exit 1
        }

        # 输出生成的 requirements.txt 的内容
        if (Test-Path "py/requirements.txt") {
          Write-Host "Generated/Updated requirements.txt:"
          Get-Content py/requirements.txt
        } else {
          Write-Error "Failed to generate or update requirements.txt"
          exit 1
        }
      shell: pwsh

    - name: Commit requirements.txt
      run: |
        # 提交更新后的 requirements.txt
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"

        if (Test-Path "py/requirements.txt") {
          git add py/requirements.txt
          git commit -m "Update requirements.txt [skip ci]"
          git push
        } else {
          Write-Host "No requirements.txt found to commit."
        }
      shell: pwsh

    - name: Setup build environment
      run: |
        # 创建必要的目录
        $dirs = @("py", "exe/original", "exe/compressed", "build", "specs")
        foreach ($dir in $dirs) {
          New-Item -ItemType Directory -Force -Path $dir
          Write-Host "Created directory: $dir"
        }

        # 下载并设置 UPX
        $upx_version = "4.2.1"
        $url = "https://github.com/upx/upx/releases/download/v${upx_version}/upx-${upx_version}-win64.zip"
        
        Invoke-WebRequest -Uri $url -OutFile upx.zip
        Expand-Archive upx.zip -DestinationPath .
        Move-Item upx-*/upx.exe . -Force
        Remove-Item upx.zip, upx-* -Recurse -Force
        
        if (Test-Path "upx.exe") {
          Write-Host "UPX installed successfully"
        } else {
          throw "Failed to install UPX"
        }
      shell: pwsh

    - name: Build EXEs
      run: |
        $ErrorActionPreference = 'Stop'
        
        # 检查是否有Python文件
        $pyFiles = Get-ChildItem "py/*.py" -ErrorAction SilentlyContinue | 
                  Where-Object { $_.BaseName -ne "runtime_hook" }  # 排除 runtime_hook.py
                  
        if (-not $pyFiles) {
          Write-Host "No Python files found in py directory"
          exit 0
        }
        
        foreach ($pyFile in $pyFiles) {
          $baseName = $pyFile.BaseName
          Write-Host "`nProcessing: $($pyFile.Name)"
          
          $common_args = @(
            "--clean",
            "--noconfirm",
            "--onefile",
            "--noconsole",
            "--name", $baseName,
            "--specpath", "specs",
            "py/$($pyFile.Name)"
          )
          
          # 构建原始版本
          Write-Host "`nBuilding original version..."
          $orig_args = $common_args + @(
            "--distpath", "exe/original",
            "--workpath", "build/original"
          )
          
          try {
            & pyinstaller $orig_args
            if (-not $?) { throw "PyInstaller failed" }
          }
          catch {
            Write-Error "Failed to build original version: $_"
            exit 1
          }
          
          # 构建压缩版本
          Write-Host "`nBuilding compressed version..."
          $comp_args = $common_args + @(
            "--distpath", "exe/compressed",
            "--workpath", "build/compressed",
            "--upx-dir", "."
          )
          
          try {
            & pyinstaller $comp_args
            if (-not $?) { throw "PyInstaller failed" }
          }
          catch {
            Write-Error "Failed to build compressed version: $_"
            exit 1
          }
          
          # 验证构建结果
          $origExe = "exe/original/$baseName.exe"
          $compExe = "exe/compressed/$baseName.exe"
          
          if (-not(Test-Path $origExe) -or -not(Test-Path $compExe)) {
            Write-Error "Build verification failed: Missing EXE files"
            exit 1
          }
          
          # 输出大小对比
          $origSize = (Get-Item $origExe).Length/1MB
          $compSize = (Get-Item $compExe).Length/1MB
          $ratio = 100 - ($compSize/$origSize*100)
          
          Write-Host "`nBuild Results for $baseName"
          Write-Host "Original: $([math]::Round($origSize, 2)) MB"
          Write-Host "Compressed: $([math]::Round($compSize, 2)) MB"
          Write-Host "Compression: $([math]::Round($ratio, 1))%"
        }
      shell: pwsh

    - name: Commit EXE files
      run: |
        # 检查是否有新的exe文件
        $hasChanges = $false
        
        foreach ($dir in @("original", "compressed")) {
          $exeFiles = Get-ChildItem "exe/$dir/*.exe" -ErrorAction SilentlyContinue
          if ($exeFiles) {
            $hasChanges = $true
            break
          }
        }
        
        if ($hasChanges) {
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add exe/original/*.exe
          git add exe/compressed/*.exe
          
          git commit -m "Update EXE files [skip ci]"
          git push
        } else {
          Write-Host "No new EXE files to commit"
        }
      shell: pwsh
